core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from account.views.account_views import LoginView


urlpatterns = [
    path("admin/", admin.site.urls),

    path("account/", include("account.urls")),
    path("pendidikan/", include("pendidikan.urls")),

    path('', LoginView.as_view()),
]

pendidikan/urls.py
from django.urls import path

from pendidikan.views import pendidikan_views

app_name = "pendidikan"

urlpatterns = [
    ############################################################################
    # VIEW
    ############################################################################
    path('', pendidikan_views.HomeView.as_view(), name="home"),
    path('personil/', pendidikan_views.PersonilListView.as_view(),
         name='personil-list'),
    path('personil/create/', pendidikan_views.PersonilCreateView.as_view(),
         name='personil-create'),

    ############################################################################
    # API
    ############################################################################
]

pendidikan/models.py
from django.db import models


class Pangkat(models.Model):
    nama = models.CharField(max_length=20, unique=True)
    counter = models.SmallIntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Pangkat'

    def __str__(self):
        return self.nama


class Korps(models.Model):
    nama = models.CharField(max_length=10, unique=True)


class Jabatan(models.Model):
    nama = models.CharField(max_length=200, unique=True)


class SumberPa(models.Model):
    nama = models.CharField(max_length=50, unique=True)

    class Meta:
        verbose_name_plural = 'Sumber PA'

    def __str__(self):
        return self.nama


class Dikmilti(models.Model):
    nama = models.CharField(max_length=50, unique=True)


class Dikbangspes(models.Model):
    nama = models.CharField(max_length=50, unique=True)


class Personil(models.Model):
    nama = models.CharField(max_length=100)
    nrp = models.CharField(max_length=30)
    tgl_lahir = models.DateField(null=True, blank=True)
    pangkat = models.ForeignKey(Pangkat, on_delete=models.CASCADE,
                                null=True, blank=True)
    jabatan = models.ForeignKey(Jabatan, on_delete=models.CASCADE,
                                null=True, blank=True,
                                related_name='personil')
    korps = models.ForeignKey(Korps, on_delete=models.CASCADE,
                              null=True, blank=True)

    def __str__(self):
        pangkat = self.pangkat.nama if self.pangkat is not None else None
        return "{} {}".format(self.nama, pangkat)


class PersonilSumberPa(models.Model):
    personil = models.ForeignKey(Personil, on_delete=models.CASCADE,
                                 related_name='personil_sumber_pa')
    sumber_pa = models.ForeignKey(SumberPa, on_delete=models.CASCADE)
    tahun = models.IntegerField()


class PersonilDikbangspes(models.Model):
    personil = models.ForeignKey(Personil, on_delete=models.CASCADE,
                                 related_name='personil_dikbangspes')
    dikbangspes = models.ForeignKey(Dikbangspes, on_delete=models.CASCADE)


class PersonilDikmilti(models.Model):
    personil = models.ForeignKey(Personil, on_delete=models.CASCADE,
                                 related_name='personil_dikmilti')
    dikmilti = models.ForeignKey(Dikmilti, on_delete=models.CASCADE)
    tahun = models.IntegerField(null=True, blank=True)

pendidikan/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import ModelForm

from pendidikan.models import Personil


class PersonilForm(ModelForm):
    class Meta:
        model = Personil
        fields = [
            'nama', 'nrp', 'tgl_lahir', 'pangkat', 'jabatan', 'korps',
        ]

        # karena di models tidak null=True dan blank=True, ubah seperti ini
        error_messages = {
            'nama': {'required': "Harap diisi"},
            'nrp': {'required': "Harap diisi"},
        }

    # field-field di bawah ini di models null=True dan blank=True
    # agar bisa insert rows dari excel ke database secara manual
    # sehingga mekanisme validasi field di form harus eksplisit seperti di bawah

    def clean_tgl_lahir(self):
        data = self.cleaned_data['tgl_lahir']

        if data is None:
            raise ValidationError("Harap diisi")

        return data

    def clean_pangkat(self):
        data = self.cleaned_data['pangkat']

        if data is None:
            raise ValidationError("Harap diisi")

        return data

    def clean_jabatan(self):
        data = self.cleaned_data['jabatan']

        if data is None:
            raise ValidationError("Harap diisi")

        return data

    def clean_korps(self):
        data = self.cleaned_data['korps']

        if data is None:
            raise ValidationError("Harap diisi")

        return data

pendidikan/views/pendidikan_views.py
from django.core.paginator import EmptyPage, Paginator
from django.db.models import Q
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from core.helpers.paginations import Pagination
from pendidikan.forms import PersonilForm
from pendidikan.models import Jabatan, Korps, Pangkat, Personil


class HomeView(Pagination, View):
    url = reverse_lazy('pendidikan:home')

    def get(self, request):
        page = 1
        if 'page' in request.GET:
            page = int(request.GET['page'])

        rows = 50
        if 'rows' in request.GET:
            rows = int(request.GET['rows'])

        jabatan_list = self.get_jabatan_list(request)

        paginator = Paginator(jabatan_list, rows)
        current_page = paginator.page(page)

        context = {
            # menu
            'home_active': 'active',

            # filter
            'rows': rows,

            # 'jabatan_list': jabatan_list,

            'current_page': current_page,

            # pagination
            'first_page_url': self.get_first_page_url(request, current_page),
            'previous_page_url': self.get_previous_page_url(request, current_page),
            'next_page_url': self.get_next_page_url(request, current_page),
            'last_page_url': self.get_last_page_url(request, current_page),
        }

        if 'q' in request.GET:
            context.update({ 'q': request.GET['q'] })

        return render(request, "pendidikan/home.html", context)

    def get_jabatan_list(self, request):
        q = Q()

        if 'q' in request.GET and len(request.GET['q']) > 0:
            q |= Q(nama__icontains=request.GET['q'])
            q |= Q(personil__pangkat__nama__icontains=request.GET['q'])
            q |= Q(personil__nama__icontains=request.GET['q'])
            q |= Q(personil__nrp__icontains=request.GET['q'])
            q |= Q(personil__personil_sumber_pa__sumber_pa__nama__icontains=request.GET['q'])
            q |= Q(personil__personil_dikmilti__dikmilti__nama__icontains=request.GET['q'])
            # q |= Q(personil__personil_dikbangspes__dikbangspes__nama__icontains=request.GET['q'])

        return Jabatan.objects.filter(q)


class PersonilListView(Pagination, View):
    def get(self, request):
        page = 1
        if 'page' in request.GET:
            page = int(request.GET['page'])

        rows = 50
        if 'rows' in request.GET:
            rows = int(request.GET['rows'])

        personil_list = self.get_personil_list()

        paginator = Paginator(personil_list, rows)
        current_page = paginator.page(page)


        context = {
            # menu
            'personil_active': 'active',

            'current_page': current_page,
        }
        return render(request, 'pendidikan/personil-list.html', context)

    def get_personil_list(self):
        return Personil.objects.all().order_by('nama')


class PersonilCreateView(View):
    def get(self, request):
        pangkat_list = Pangkat.objects.all().order_by('counter')
        jabatan_list = Jabatan.objects.all().order_by('nama')
        korps_list = Korps.objects.all().order_by('nama')

        context = {
            'form_title': "Tambah Personil",

            'pangkat_list': pangkat_list,
            'jabatan_list': jabatan_list,
            'korps_list': korps_list,
        }

        return render(request, 'pendidikan/personil-form.html', context)

    def post(self, request):
        context = self.get_context(request)

        form = PersonilForm(request.POST)

        if not form.is_valid():
            context = self.get_error_context(context, request, form)
            return render(request, 'pendidikan/personil-form.html', context)

        form.save()

        # TODO redirect ke update form/personil detail
        
        return render(request, 'pendidikan/personil-form.html', context)

    def get_context(self, request):
        context = {
            'form_title': 'Tambah Personil',

            # populate dropdown
            'pangkat_list': Pangkat.objects.all().order_by('counter'),
            'jabatan_list': Jabatan.objects.all().order_by('nama'),
            'korps_list': Korps.objects.all().order_by('nama'),
        }

        return context

    def get_error_context(self, context, request, form):
        context.update({
            # render feedback message di setiap field
            'errors': form.errors,

            # render global message
            'message': "Isian tidak sesuai",
        })

        # jika field nama sudah diisi, tetap tampilkan nama di placeholder
        if 'nama' in request.POST:
            context['nama'] = request.POST['nama']

        # idem
        if 'nrp' in request.POST:
            context['nrp'] = request.POST['nrp']

        # idem
        if 'tgl_lahir' in request.POST:
            context['tgl_lahir'] = request.POST['tgl_lahir']

        # convert ke integer equal operator dropdown butuh integer
        if 'pangkat' in request.POST:
            context['selected_pangkat'] = int(request.POST['pangkat'])

        # idem
        if 'jabatan' in request.POST:
            context['selected_jabatan'] = int(request.POST['jabatan'])

        # idem
        if 'korps' in request.POST:
            context['selected_korps'] = int(request.POST['korps'])
        
        if '__all__' in form.errors:
            context['message'] = form.errors['__all__'].as_text()

        return context

pendidikan/templates/pendidikan/home.html
{% extends 'components/base/001-base.html' %}

{% load static %}

{% block content %}
  <div class="container-fluid mt-4">
    <div class="row" style="align-items: center;">
      <div class="col-9">
        <p>Menampilkan <strong>{{ current_page.start_index|default:0 }} - {{ current_page.end_index|default:0 }}</strong> dari <strong>{{ current_page.paginator.count|default:0 }}</strong> data</p>
      </div>
      <div class="col-3">
        <form method="get">
          <div class="input-group input-group-sm mb-3">
            <input type="text" class="form-control" name="q" value="{{ q }}" placeholder="Cari personil, pendidikan...">
            <button class="btn btn-outline-secondary" type="submit" id="button-addon2">Cari</button>
          </div>
        </form>
        <!-- <button class="btn btn-sm btn-outline-secondary">Filter</button> -->
      </div>
    </div>

    <table class="table table-sm">
      <thead>
        <tr>
          <th>No</th>
          <th>Jabatan</th>
          <th colspan="2">Pangkat</th>
          <th>Nama</th>
          <th>NRP</th>
          <th>Sumber PA</th>
          <th>Dikmilti</th>
          <th>Dikbangspes</th>
        </tr>
      </thead>
      <tbody>
        {% if current_page %}
          {% for jabatan in current_page %}
          <tr>
            <td>{{ forloop.counter0|add:current_page.start_index }}</td>
            <td>{{ jabatan.nama }}</td>
            <td>{{ jabatan.personil.first.pangkat.nama }}</td>
            <td>{{ jabatan.personil.first.korps.nama }}</td>
            <td>{{ jabatan.personil.first.nama }}</td>
            <td>{{ jabatan.personil.first.nrp }}</td>
            <td>{{ jabatan.personil.first.personil_sumber_pa.first.sumber_pa.nama }} {{ jabatan.personil.first.personil_sumber_pa.first.tahun }}</td>
            <td>{{ jabatan.personil.first.personil_dikmilti.first.dikmilti.nama }} {{ jabatan.personil.first.personil_dikmilti.first.tahun|default:'' }}</td>
            <td>
              {% for personil_dikbangspes in jabatan.personil.first.personil_dikbangspes.all %}
                <div>{{ personil_dikbangspes.dikbangspes.nama }}</div>
              {% endfor %}
            </td>
          </tr>
          {% endfor %}
        {% else %}
          <tr>
            <td colspan="9" class="text-center">Tidak ada data</td>
          </tr>
        {% endif %}
      </tbody>
    </table>
  </div>

  {% include 'components/pagination/001-pagination.html' %}
{% endblock %}

pendidikan/templates/pendidikan/personil-form.html
{% extends 'components/base/001-base.html' %}

{% load static %}

{% block css %}
  <link rel="stylesheet" type="text/css" href="{% static 'core/vendors/flatpickr/flatpickr.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'core/vendors/flatpickr/plugins/monthSelect/style.css' %}">

  <style type="text/css">
    body {
      background-color: #f0f0f0;
    }

    .success-message {
      background-color: forestgreen;
      color: white;
    }

    .error-message {
      background-color: indianred;
      color: white;
    }

    #close-btn {
      text-decoration: none;
      color: white;
    }

    #review-form {
      background-color: white;
      padding: 30px;
    }

    #form-title {
      margin-bottom: 20px;
    }
  </style>
{% endblock %}

{% block content %}
  {% if message %}
    <div id="notification-message" class="d-flex justify-content-between {% if errors %}error-message{% elif success %}success-message{% endif %}">
      <div class="p-2"></div>
      <div class="p-2">{{ message }}</div>
      <div class="p-1"><a role="button" id="close-btn" class="btn btn-link btn-sm" href="#">X</a></div>
    </div>
  {% endif %}

  <div class="container mt-5">
    <div class="row mb-5">
      <div class="col-12 col-md-2 col-lg-3"></div>

      <div class="col-12 col-md-8 col-lg-6" id="review-form">
        <h4 id="form-title">{{ form_title }}</h4>

        <form method="post" class="row g-3">
          {% csrf_token %}

          <div class="col-12">
            <label for="nama-input" class="form-label">Nama</label>
            <input id="nama-input" type="text" name="nama" value="{{ nama }}" class="form-control {% if errors.nama %}is-invalid{% endif %}">
            <div class="invalid-feedback">
              {{ errors.nama.as_text }}
            </div>
          </div>

          <div class="col-12">
            <label for="nrp-input" class="form-label">NRP</label>
            <input id="nrp-input" type="text" name="nrp" value="{{ nrp }}" class="form-control {% if errors.nrp %}is-invalid{% endif %}">
            <div class="invalid-feedback">
              {{ errors.nrp.as_text }}
            </div>
          </div>

          <div class="col-12">
            <label for="tgl-lahir-input" class="form-label">Tanggal Lahir</label>
            <input id="tgl-lahir-input" type="text" name="tgl_lahir" value="{{ tgl_lahir }}" class="form-control {% if errors.tgl_lahir %}is-invalid{% endif %}">
            <div class="invalid-feedback">
              {{ errors.pangkat.as_text }}
            </div>
          </div>

          <div class="col-12">
            <label for="pangkat-dropdown" class="form-label">Pangkat</label>
            <select class="form-select {% if errors.pangkat %}is-invalid{% endif %}" id="pangkat-dropdown" name="pangkat">
              <option selected disabled>Pilih pangkat</option>
              {% for pangkat in pangkat_list %}
                <option value="{{ pangkat.id }}" {% if pangkat.id == selected_pangkat %}selected{% endif %}>{{ pangkat.nama }}</option>
              {% endfor %}
            </select>
            <div class="invalid-feedback">
              {{ errors.pangkat.as_text }}
            </div>
          </div>

          <div class="col-12">
            <label for="jabatan-dropdown" class="form-label">Jabatan</label>
            <select class="form-select {% if errors.jabatan %}is-invalid{% endif %}" id="jabatan-dropdown" name="jabatan">
              <option selected disabled>Pilih jabatan</option>
              {% for jabatan in jabatan_list %}
                <option value="{{ jabatan.id }}" {% if jabatan.id == selected_jabatan %}selected{% endif %}>{{ jabatan.nama }}</option>
              {% endfor %}
            </select>
            <div class="invalid-feedback">
              {{ errors.jabatan.as_text }}
            </div>
          </div>

          <div class="col-12">
            <label for="korps-dropdown" class="form-label">Korps</label>
            <select class="form-select {% if errors.korps %}is-invalid{% endif %}" id="korps-dropdown" name="korps">
              <option selected disabled>Pilih korps</option>
              {% for korps in korps_list %}
                <option value="{{ korps.id }}" {% if korps.id == selected_korps %}selected{% endif %}>{{ korps.nama }}</option>
              {% endfor %}
            </select>
            <div class="invalid-feedback">
              {{ errors.korps.as_text }}
            </div>
          </div>

          <div class="col-12 text-end">
            <a type="button" class="btn btn-link" href="{% url 'pendidikan:personil-list' %}" style="text-decoration: none;">Cancel</a>
            <button type="submit" class="btn btn-success" id="submit-button">Submit</button>
          </div>
        </form>
      </div>

      <div class="col-12 col-md-2 col-lg-3"></div>
    </div>
  </div>
{% endblock %}

{% block javascript %}
  <script type="text/javascript" src="{% static 'core/vendors/flatpickr/flatpickr.min.js' %}" ></script>

  <script type="text/javascript">
    flatpickr('#tgl-lahir-input', {})
  </script>
{% endblock %}

pendidikan/templates/pendidikan/personil-list.html
{% extends 'components/base/001-base.html' %}

{% load static %}

{% block content %}
  <div class="container-fluid mt-4">
    <div class="row mb-3">
      <div class="col-12">
        <a class="btn btn-sm btn-success bi bi-plus-lg" href="{% url 'pendidikan:personil-create' %}"> Tambah Personil</a>
      </div>
    </div>
    <table class="table table-sm">
      <thead>
        <tr>
          <th>No</th>
          <th>Nama</th>
          <th>Pangkat</th>
          <th>Jabatan</th>
          <th>NRP</th>
          <th>Tanggal Lahir</th>
        </tr>
      </thead>
      <tbody>
        {% for personil in current_page %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ personil.nama }}</td>
            <td>{{ personil.pangkat.nama }} {{ personil.korps.nama }}</td>
            <td>{{ personil.jabatan.nama }}</td>
            <td>{{ personil.nrp }}</td>
            <td>{{ personil.tgl_lahir|date:'d-m-Y' }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

pendidikan/templates/pendidikan/personil.html
{% extends 'components/base/001-base.html' %}

{% load static %}

{% block content %}
  <div class="container-fluid mt-4">
    <div class="row">
      <div class="col-12">
        <button class="btn btn-sm btn-success bi bi-plus-lg"> Tambah Personil</button>
      </div>
    </div>
    <table class="table table-sm">
      <thead>
        <tr>
          <th>No</th>
          <th>Nama</th>
          <th>Pangkat</th>
          <th>Jabatan</th>
          <th>NRP</th>
          <th>Tanggal Lahir</th>
        </tr>
      </thead>
      <tbody>
        {% for personil in current_page %}
          <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ personil.nama }}</td>
            <td>{{ personil.pangkat.nama }} {{ personil.korps.nama }}</td>
            <td>{{ personil.jabatan.nama }}</td>
            <td>{{ personil.nrp }}</td>
            <td>{{ personil.tgl_lahir|date:'d-m-Y' }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}